import type { Config } from 'tailwindcss';

export default {
   content: ['./index.html', './src/**/*.{ts,tsx}'],
   theme: {
      extend: {
         colors: {
            primary: '#005bbf',
            'on-primary': '#ffffff',
            'primary-container': '#1a73e8',
            'on-primary-container': '#ffffff',
            'primary-fixed': '#d8e2ff',
            'primary-fixed-dim': '#adc7ff',
            'on-primary-fixed': '#001a41',
            'on-primary-fixed-variant': '#004493',
            'inverse-primary': '#adc7ff',
            secondary: '#006e2c',
            'on-secondary': '#ffffff',
            'secondary-container': '#86f898',
            'on-secondary-container': '#00722f',
            'secondary-fixed': '#89fa9b',
            'secondary-fixed-dim': '#6ddd81',
            'on-secondary-fixed': '#002108',
            'on-secondary-fixed-variant': '#005320',
            tertiary: '#b81d17',
            'on-tertiary': '#ffffff',
            'tertiary-container': '#dc392c',
            'on-tertiary-container': '#ffffff',
            'tertiary-fixed': '#ffdad5',
            'tertiary-fixed-dim': '#ffb4a9',
            'on-tertiary-fixed': '#410001',
            'on-tertiary-fixed-variant': '#930004',
            error: '#ba1a1a',
            'on-error': '#ffffff',
            'error-container': '#ffdad6',
            'on-error-container': '#93000a',
            surface: '#f7f9ff',
            'on-surface': '#181c20',
            'surface-dim': '#d7dae0',
            'surface-bright': '#f7f9ff',
            'surface-variant': '#dfe3e8',
            'on-surface-variant': '#414754',
            'surface-container-lowest': '#ffffff',
            'surface-container-low': '#f1f4fa',
            'surface-container': '#ebeef4',
            'surface-container-high': '#e5e8ee',
            'surface-container-highest': '#dfe3e8',
            'surface-tint': '#005bc0',
            'inverse-surface': '#2d3135',
            'inverse-on-surface': '#eef1f7',
            background: '#f7f9ff',
            'on-background': '#181c20',
            outline: '#727785',
            'outline-variant': '#c1c6d6',
         },
         fontSize: {
            'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
            'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
            'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
            'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
            'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
            'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
         },
         spacing: {
            xs: '4px',
            sm: '8px',
            base: '4px',
            md: '16px',
            lg: '24px',
            xl: '32px',
            gutter: '16px',
            'container-margin': '24px',
         },
         borderRadius: {
            DEFAULT: '0.25rem',
            lg: '0.5rem',
            xl: '0.75rem',
            full: '9999px',
         },
      },
   },
} satisfies Config;
